### ISSUE TITLE
Google API Keys

### ISSUE THREAD

**Issue by clifordmlotshwa** [chris48s/cakephp-geocoder#1]
I get this when i try to use cakephp-geocoder "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/"

**Comment by chris48s** [comment]
The plugin is just a simple wrapper for the google maps geocoding api. This is an issue with your interaction with the google maps geocoding api, not the plugin.
If you call https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA (for example) you'll find you get the same error.

See google's docs:
developer guide - https://developers.google.com/maps/documentation/geocoding/intro
usage limits - https://developers.google.com/maps/documentation/geocoding/usage-limits

Maybe if you're unexpectedly hitting the limit, it is because you are using shared hosting or behind a NAT?

Either way, the plugin is behaving as expected.

At the moment the plugin only supports anonymous access to the API. Perhaps the ability to optionally accept an API key would be a useful feature for heavy users. Happy to receive a PR for this.

**Comment by reloxx13** [comment]
it does accept the key over the 2nd parameter, just add your key
$parameters["key"] = "YOUR_API_KEY";
->geolocate($location, $parameters);

but google requires https and in the code its hardcoded to http, i made 2 pull request to chaneg it to https.
@chris48s  pl0x accept the pull request or take a look by urself 👍

**Comment by chris48s** [comment]
Hi @reloxx13

Thanks for having a look at this. I have merged your contributions, [added a note to the docs](https://github.com/chris48s/cakephp-geocoder#api-keys) and [released a new version to packagist](https://packagist.org/packages/chris48s/cakephp-geocoder#1.0.1).

@clifordmlotshwa - Update your dependency to version `1.0.1` and see the docs if you are still interested in this feature.
